import Head from "next/head";

import useTranslation from "next-translate/useTranslation";

export default function Home() {
  const { t, lang } = useTranslation("test");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h2 className=" text-2xl">{t("home")}</h2>
        {t("description")}
      </div>
    </>
  );
}
