import Head from "next/head";

import useTranslation from "next-translate/useTranslation";

export default function Home() {
  const { t, lang } = useTranslation("test");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>This is it</h1>
        {t("lang")} is in "{lang}"
      </div>
    </>
  );
}
