import React from "react";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import Sider from "@/components/Sider";
import Head from "next/head";

const MainLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Next.js Practice | Anandu Babu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/next.svg" />
      </Head>

      <div>
        <div className=" bg-orange-500 flex justify-end py-1 px-4 text-white">
          <LanguageSwitcher />
        </div>
        <div className="flex">
          <Sider />

          <div style={{ padding: "24px" }}>{children}</div>
        </div>
      </div>
    </>
  );
};

export default MainLayout;
